# Grafana Datasource Provisioning for Prometheus
# Documentation: https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://greenstack-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 60s
      # Enable Prometheus query editor features
      customQueryParameters: ''
      # Exemplars configuration (for distributed tracing)
      exemplarTraceIdDestinations: []
    version: 1
    uid: prometheus-greenstack
